apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/XenitAB/gatekeeper-library/main/library/assigns/pod-default-seccomp.yaml
  - github.com/open-policy-agent/gatekeeper-library/library
